AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Creates the IAM Role that is used to execute all Sceptre tasks
  in this repo. 

Parameters:
  CICDRoleArn:
    Type: String
    Description: The ARN of the IAM role used by CICD

  DeploymentRoleName:
    Type: String
    Description: Name to use for this role

Resources:
  SceptreDeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      Path: '/'
      RoleName: !Join ['-', [!Ref DeploymentRoleName, !Ref AWS::Region]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref CICDRoleArn
            Action: 'sts:AssumeRole'

  SceptreDeploymentRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: BaseSceptreDeploymentPolicy
      Roles:
      - Ref: SceptreDeploymentRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - cloudformation:CreateStack
          - cloudformation:DeleteStack
          - cloudformation:DescribeStackEvents
          - cloudformation:DescribeStackResource
          - cloudformation:DescribeStackResources
          - cloudformation:DescribeStacks
          - cloudformation:GetStackPolicy
          - cloudformation:GetTemplate
          - cloudformation:GetTemplateSummary
          - cloudformation:ListStackResources
          - cloudformation:ListStacks
          - cloudformation:SetStackPolicy
          - cloudformation:TagResource
          - cloudformation:UntagResource
          - cloudformation:UpdateStack
          - cloudformation:UpdateTerminationProtection
          - cloudformation:ValidateTemplate
          - cloudformation:CreateChangeSet
          - cloudformation:DeleteChangeSet
          - cloudformation:DescribeChangeSet
          - cloudformation:ExecuteChangeSet
          - cloudformation:ListChangeSets
          Resource:
          - "*"

Outputs:
  SceptreRoleArn:
    Value:
      Fn::GetAtt:
      - SceptreDeploymentRole
      - Arn
    Description: Arn of the role to use for all sceptre deployments
    Export:
      Name: SceptreDeploymentRoleArn
